# Site settings
title: ReidHolmes
email: name.reidholmes@gmail.com
description: '上善若水，厚德载物，人淡如菊。"Technology make the world a better place." 看得越多越沉默 但行好事，莫问前程'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://reidholmes.github.io" # the base hostname & protocol for your site
twitter_username: namereidholmes
github_username:  ReidHolmes

# Build settings
markdown: kramdown

permalink: /:year/:month/:day/breezedeus-:title.html

#gems: [mathml.jb]

# new
#comments: true

#paginate: 5
#paginate_path: "/page:num/"